import java.awt.Desktop

plugins {
	id 'java'
	id 'org.springframework.boot' version '3.5.5'
	id 'io.spring.dependency-management' version '1.1.7'
    id 'jacoco'
    id 'org.sonarqube' version '4.4.1.3373'
    id 'io.qameta.allure' version '2.11.2'
}

group = 'ExpooCode'
version = '0.0.1-SNAPSHOT'
description = 'Demo project for Spring Boot'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-web'
	compileOnly 'org.projectlombok:lombok'
	runtimeOnly 'org.mariadb.jdbc:mariadb-java-client'
	annotationProcessor 'org.projectlombok:lombok'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
	// https://mvnrepository.com/artifact/org.springdoc/springdoc-openapi-starter-webmvc-ui
	implementation("org.springdoc:springdoc-openapi-starter-webmvc-ui:2.8.12")

	// MapStruct para mapeo automático
	implementation 'org.mapstruct:mapstruct:1.6.3'
	annotationProcessor 'org.mapstruct:mapstruct-processor:1.6.3'
	// Para usar MapStruct con Lombok
	annotationProcessor 'org.projectlombok:lombok-mapstruct-binding:0.2.0'
	// JUnit 5 (incluido en spring-boot-starter-test)
	testImplementation 'org.springframework.boot:spring-boot-starter-test'

	// Mockito (incluido en spring-boot-starter-test)
	testImplementation 'org.mockito:mockito-core'
	testImplementation 'org.mockito:mockito-junit-jupiter'

	// AssertJ para assertions fluidas
	testImplementation 'org.assertj:assertj-core'

    // Allure para reportes visuales
    testImplementation 'io.qameta.allure:allure-junit5:2.24.0'
    testImplementation 'io.qameta.allure:allure-java-commons:2.24.0'


    implementation 'io.jsonwebtoken:jjwt-api:0.12.3'
    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.12.3'
    runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.12.3'

}

tasks.named('test') {
    useJUnitPlatform()
    finalizedBy jacocoTestReport, allureReport  // tras los test se generan los relportes con JaCoCo + Allure
}

jacoco {
    toolVersion = "0.8.10"
}

jacocoTestReport {
    dependsOn test
    reports {
        xml.required = true   // necesario para SonarQube
        html.required = true  // reporte navegable local
    }
    finalizedBy jacocoTestCoverageVerification
}

jacocoTestCoverageVerification {
    violationRules {
        rule {
            limit {
                minimum = 0.30 // ejemplo: exige al menos 80% cobertura
            }
        }
    }
}

allure {
    version = "2.24.0"     // versión de Allure Report
    autoconfigure = true   // configura automáticamente JUnit 5 listener
    aspectjweaver = true   // necesario para anotaciones @Step, @Attachment

}

// Configuración SonarQube
sonarqube {
    properties {
        property "sonar.projectKey", "ExpooCode-Project"
        property "sonar.projectName", "ExpooCode"
        property "sonar.host.url", "http://localhost:9000"
        property "sonar.login", "sqp_c6a080fb6621552815142142a8088e46050ef5c7" // genera en SonarQube
        //property "sonar.login", "squ_60fbe61d7fd0a74c4b3a7873243341d19419584a"
        property "sonar.sources", "src/main/java"
        property "sonar.tests", "src/test/java"
        property "sonar.java.binaries", "build/classes/java/main"
        property "sonar.coverage.jacoco.xmlReportPaths", "build/reports/jacoco/test/jacocoTestReport.xml"

        property "sonar.gradle.skipCompile", "true"

    }
}

// Tarea extra para abrir el reporte de Allure en navegador automáticamente
tasks.register('openAllureReport') {
    dependsOn allureReport
    doLast {
        Desktop.getDesktop().browse(new File("$buildDir/reports/allure-report/index.html").toURI())
    }
}
