# Puerto dinámico de Render
server.port=${PORT:8080}

# Base de datos PostgreSQL (Render)
spring.datasource.url=${DATABASE_URL}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate (producción)
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=false

# Connection pool
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000

# Logging (solo info importante)
logging.level.root=INFO
logging.level.ExpooCode.ExpooCode=INFO
logging.level.org.springframework.security=WARN